name: Go Code Check

on:
  pull_request:
    branches: [ main ]
    paths:
      - '**.go'

jobs:
  validate:
    name: Validate Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '^1.18' # Use the version of Go that your project requires

      - name: Install goimports
        run: go install golang.org/x/tools/cmd/goimports@latest

      - name: Install golint
        run: go install golang.org/x/lint/golint@latest

      - name: Check formatting with gofmt
        run: |
          if [ -n "$(gofmt -l .)" ]; then
            echo "The following files need to be formatted with gofmt:"
            gofmt -l .
            exit 1
          fi

      - name: Check imports with goimports
        run: |
          if [ -n "$(goimports -l .)" ]; then
            echo "The following files have import issues that need to be fixed with goimports:"
            goimports -l .
            exit 1
          fi

      - name: Lint with golint
        run: |
          if [ -n "$(golint ./...)" ]; then
            echo "golint has detected issues with the code."
            golint ./...
            exit 1
          fi

      - name: Vet
        run: |
          if ! go vet ./...; then
            echo "go vet has found issues with the code."
            exit 1
          fi
